title: "Bhanu Teja Nellore"
markdown: CommonMarkGhPages
remote_theme: pmarsceill/just-the-docs


# just-the-docs options
# Aux links for the upper right navigation
aux_links:
  # "View source on GitHub":
  #   - "//github.com/nellorebhanuteja/nellorebhanuteja.github.io"
  "LinkedIn":
    - "https://www.linkedin.com/in/bhanu-teja-nellore-b9b729165/?originalSubdomain=in"
  "Google Scholar":
    - "https://scholar.google.co.in/citations?user=NCXdaIEAAAAJ&hl=en"
    
aux_links_new_tab: true

# search:
#   button: true
  
  
# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
